[general]
live_config_reload = true
import = ["~/.config/alacritty/themes/b-side/b-side.toml"]



[font]
size = 10.0

[font.normal]
family = "Hurmit Nerd Font"
style = "Medium"

[font.bold]
family = "Hurmit Nerd Font"
style = "Heavy"

[font.italic]
family = "Hurmit Nerd Font"
style = "Medium Italic"

[font.bold_italic]
family = "Hurmit Nerd Font"
style = "Heavy Italic"

